modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/jaredlll08/bigshot/issues"
license = "MIT"

[[mods]]
modId = "bigshot"
updateJSONURL = "https://updates.blamejared.com/get?n=bigshot&gv=1.20.1"
version = "${file.jarVersion}"
displayName = "BigShot"
displayURL = "https://minecraft.curseforge.com/projects/bigshot"
authors = "Jaredlll08"
logoFile = "icon.png"
description = '''
Creates big screenshots
'''
itemIcon = "minecraft:compass"
[[dependencies.bigshot]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
[[dependencies.bigshot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"